blog/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('search/', search, name='search'),
    path('', blog, name='blog'),
    path('create/', create, name='create'),
    path('<str:slug>/update', update, name='articles_update'),
    path('<str:slug>/delete/', delete, name='articles_delete'),
    path('<str:slug>/', details, name='details'),
    path('tag/<str:tag>/', articles_tag_list, name='articles_tag'),
    path('category/<str:category>/', articles_category_list, name='articles_category'),
]

first_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from core.views import about_us, contacts, questions
from blog.views import blog, details
from blog.urls import urlpatterns as blog_urls
from django.contrib.auth import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', about_us, name="about_us"),
    path('', about_us, name="index"),
    path('contacts/', contacts, name="contacts"),
    path('questions/', questions, name="questions"),
    path('blog/', include(blog_urls)),
    path('members/', include('members.urls')),
    path('shop/', include('shop.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

members/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('login/', login_view, name='login'),
    path('profile/', profile_view, name='profile'),
    path('logout/', logout_view, name='logout'),
    path('signup/', singup_view, name='signup'),
    path('profile/edit/', profile_edit, name='profile_edit'),
]

blog/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User
from django.utils.text import slugify

# Create your models here
class Article(models.Model):
    ACTIVE = 'active'
    DRAFT = 'draft'
    
    STATUS_CHOICES = (
        (ACTIVE, 'Active'),
        (DRAFT, 'Draft')
    )
    
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='articles', verbose_name='Author', default=1)
    category = models.ForeignKey('Category', on_delete=models.CASCADE, related_name='articles', default=1, verbose_name='Category')
    tags = models.ManyToManyField('Tag', related_name='articles', verbose_name='Tags')
    title = models.CharField(max_length=255, verbose_name='Title')
    slug = models.SlugField(verbose_name='URL', unique=True)
    discription = models.TextField(verbose_name='Article discription')
    text = RichTextField(verbose_name='Контент')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Created on')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Updated on')
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default=DRAFT, verbose_name='Status')
    image = models.ImageField(upload_to='articles/', verbose_name='Image', blank=True, null=True)
    
    def __str__(self):
        return f'{self.title}'
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)
    
class Category(models.Model):
    name = models.CharField(max_length=255, verbose_name='Category name')
    slug = models.SlugField(verbose_name='URL', default='', unique=True)
    
    def __str__(self):
        return f'{self.name}'
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

class Tag(models.Model):
    name = models.CharField(max_length=255, verbose_name='Tag name', unique=True)
    slug = models.SlugField(verbose_name='URL', default='', unique=True)

    def __str__(self):
        return f'{self.name}'
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=255, verbose_name='User name')
    email = models.EmailField(verbose_name='Email')
    content = RichTextField(verbose_name='Comment')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Created on')

    def __str__(self):
        return f'{self.article.title} - {self.content}'

members/models.py
from django.db import models

# Create your models here.

members/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User 

class SingupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username','email','password1','password2')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        #widget is a html form element
        self.fields['username'].widget.attrs.update({'class':'form-control'})
        self.fields['email'].widget.attrs.update({'class':'form-control'})
        self.fields['password1'].widget.attrs.update({'class':'form-control'})
        self.fields['password2'].widget.attrs.update({'class':'form-control'})

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data['email']

        if commit:
            user.save()
        return user


class EditProfileForm(UserChangeForm):
    password = forms.CharField(widget=forms.TextInput(attrs={'type':'hidden'}), required=False)
    class Meta:
        model = User
        fields = ('username','email','first_name','last_name')
        widgets = {
            'username':forms.TextInput(attrs={'class':'form-control'}),
            'email':forms.TextInput(attrs={'class':'form-control'}),
            'first_name':forms.TextInput(attrs={'class':'form-control'}),
            'last_name':forms.TextInput(attrs={'class':'form-control'}),
        }

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data['email']
        password = self.cleaned_data["new_password1"]
        self.user.set_password(password)

        if commit:
            user.save()
        return user

members/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required

from .forms import SingupForm, EditProfileForm
# Create your views here.

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            login(request, form.get_user())
            next_url = request.GET.get('next')
            if next_url:
                return redirect(next_url)
            else:
                return redirect('index')
    else:
        form = AuthenticationForm()
    
    return render(request, 'members/login_or_signup.html', {'title':'Login','form':form})

def singup_view(request):
    if request.method == 'POST':
        form = SingupForm(request.POST)
        if form.is_valid():
            form.save()

            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')

            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('index')
    else:
        form = SingupForm()

    return render(request, 'members/login_or_signup.html', {'title':'Signup','form':form})

def profile_view(request):
    return render(request, 'members/profile.html', {'title':'Profile'})

@login_required
def profile_edit(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect('profile')
    else:
        form = EditProfileForm(instance=request.user)
        return render(request, 'members/login_or_signup.html', {'title':'Edit Profile','form':form})

@login_required
def logout_view(request):
    logout(request)
    return redirect('index')

members/templates/members/login.html
{% extends 'core/base.html'%}

{% block title %} {{title}} {% endblock %}

{% block content %}
    <h1>{{title}}</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="btn btn-primary" type="submit" value="Submit">
    </form>
{% endblock %}

members/templates/members/login_or_signup.html
{% extends 'core/base.html'%}

{% block title %} {{title}} {% endblock %}

{% block content %}
    <h1>{{title}}</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="btn btn-primary" type="submit" value="Submit">
    </form>
{% endblock %}

members/templates/members/profile.html
{% extends 'core/base.html'%}

{% block title %} {{title}} {% endblock %}

{% block content %}
<div class= 'row'>
    <div class="col-md-4 mb-3">
        <div class="card">
          <div class="card-body">
            <div class="d-flex flex-column align-items-center text-center">
              <img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="Admin" class="rounded-circle" width="150">
              <div class="mt-3">
                <h4>{{user.username}}</h4>
                <p class="text-secondary mb-1">{{user.email}}</p>
                <p class="text-muted font-size-sm">{{user.profile.bio}}</p>
                {% comment %} <p class="text-muted font-size-sm">Bay Area, San Francisco, CA</p>
                <button class="btn btn-primary">Follow</button>
                <button class="btn btn-outline-primary">Message</button> {% endcomment %}
              </div>
            </div>
          </div>
        </div>
        <div class="card mt-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
              <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-globe mr-2 icon-inline"><circle cx="12" cy="12" r="10"></circle><line x1="2" y1="12" x2="22" y2="12"></line><path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"></path></svg>Website</h6>
              <span class="text-secondary">https://bootdey.com</span>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
              <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-github mr-2 icon-inline"><path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path></svg>Github</h6>
              <span class="text-secondary">bootdey</span>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
              <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-twitter mr-2 icon-inline text-info"><path d="M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z"></path></svg>Twitter</h6>
              <span class="text-secondary">@bootdey</span>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
              <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-instagram mr-2 icon-inline text-danger"><rect x="2" y="2" width="20" height="20" rx="5" ry="5"></rect><path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"></path><line x1="17.5" y1="6.5" x2="17.51" y2="6.5"></line></svg>Instagram</h6>
              <span class="text-secondary">bootdey</span>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
              <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-facebook mr-2 icon-inline text-primary"><path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z"></path></svg>Facebook</h6>
              <span class="text-secondary">bootdey</span>
            </li>
          </ul>
        </div>
      </div>
    <div class='col-md-4'>
        <div class="card mb-3">
            <div class="card-body">
              <div class="row">
                <div class="col-sm-3">
                  <h6 class="mb-0">Full Name</h6>
                </div>
                <div class="col-sm-9 text-secondary">
                  {{ request.user.get_full_name }}
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <h6 class="mb-0">Email</h6>
                </div>
                <div class="col-sm-9 text-secondary">
                    {{ request.user.email }}
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-12">
                  <a class="btn btn-info " href="{% url 'profile_edit' %}">Edit</a>
                </div>
              </div>
            </div>
        </div>
    </div>
</div>



{% comment %} <div class='col-md-8'>
<form action='' method='post'>
    {% csrf_token %}
    <div class='form-group'>
        <label for='id_title'>{{ form.username.label }}</label>
        <input type='text' name='username' class='form-control' id='id_username' value='{{ form.username.value }}'>
    </div>
    <div class='form-group'>
        <label for='id_title'>{{ form.email.label }}</label>
        <input type='text' name='email' class='form-control' id='id_email' value='{{ form.email.value }}'>
    </div>
    <div class='form-group'>
        <label for='id_title'>{{ form.first_name.label }}</label>
        <input type='text' name='first_name' class='form-control' id='id_first_name' value='{{ form.first_name.value }}'>
    </div>
    <div class='form-group'>
        <label for='id_title'>{{ form.last_name.label }}</label>
        <input type='text' name='last_name' class='form-control' id='id_last_name' value='{{ form.last_name.value }}'>
    </div>
    <input type='submit' value='Submit' class='btn btn-primary'>
</form>
</div> {% endcomment %}
{% endblock %}